name: SimpleLootCrates
version: ${minecraft.plugin.version}
main: de.minebench.simplelootcrates.SimpleLootCrates
api-version: 1.13
authors: [Phoenix616]
description: A simple loot crate plugin
commands:
  simplelootcrates:
    aliases:
      - simplelootcrate
      - slc
      - crates
      - crate
      - lootcrate
      - lootcrates
    description: Main plugin command
    usage: /<command> gui|add|list|get|give|reload
    permission: simplelootcrates.command